[package]
name = "statusbar-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
battery = "0.7"
serde = { version = "1.0.226", features = ["derive"] }
serde_json = "1.0"
openweather_sdk = "0.1.8"
reqwest = { version = "0.12", features = ["blocking"] }